JetBrains/kotlin-multiplatform-dev-docs

- topics/multiplatform-samples.md
Confetti sample now uses Decompose. Updated multiplatform-samples.md, replaced `kmm-viewmodel` with `decompose`.
cc: @joreilly
> Updated Confetti sample in multiplatform-samples.md

- topics/compose-onboard/compose-multiplatform-explore-composables.md
When I was going throught the documentation I realized that a ´t´ is missing from MainActivity.k. This is a minor issues but I thought it might help other beginners in the future.
> Change name of MainActivity extension from .k to .kt

- topics/multiplatform-samples.md
While reviewing the addition of Twine internally, we decided that the Bookshelf sample was outdated and not representative of KMP anymore.
> update: remove Bookshelf sample as outdated

- topics/multiplatform-samples.md
The `kotlin-multiplatform` topic is dominated by much-used libraries, which makes it harder to discover sample projects even if they have a couple hundred starts. This PR adds a link to the "kotlin-multiplatform-sample" topic (which currently isn't populated), which can be used for this specific use case.
> Add kotlin-multiplatform-sample topic

- topics/multiplatfrom-onboard/multiplatform-upgrade-app.md
Different styles of dependencies don't work well with copy-paste. This is a quick fix for the tutorial experience. In the future, we'll probably update this step to use the version catalog explicitly.
> fix: change the syntax of the lifecycle-viewmodel-compose dependency

- topics/compose/compose-lifecycle.md
Two entries in the table were swapped. Gaining focus resumes the Desktop app, while losing it makes it paused.
> Fix callback names in lifecycle table

- topics/multiplatform-integrate-in-existing-app.md
The issue with the changes: https://youtrack.jetbrains.com/issue/KT-63821
> update: embedAndSign doesn't need Framework Search Path anymore

- topics/compose-onboard/compose-multiplatform-getting-started.md
- topics/multiplatfrom-onboard/multiplatform-getting-started.md
a temporary workaround for the duplicated Get Started issue: it's bad timing for a revolution with removing pages and changing links, but we can try renaming instead
> update: rename get started in tutorials

- topics/compose/compose-compatibility-and-versioning.md
With Kotlin 2.0.0 and the Compose compiler Gradle plugin, there is no need to manually juggle different compiler plugins to try new versions.
> update: remove the old compatibility section and clarify the platform limitations

- topics/multiplatform-samples.md
Hallo, Rijksmuseum is Kotlin and Compose Multiplatform app that offers an immersive way to explore the art collection of the renowned Rijksmuseum in Amsterdam. The project is multi-modular and uses compose for all platforms (Android, iOS, desktop and web). It also showcases topics like DI, Networking, Navigation, Caching and Sharing build logic between subprojects/modules...
If this is a good sample for people, please include it in the doc, or else feel free to close the PR.
Here is the repo: https://github.com/fethij/rijksmuseum
> Add Rijksmuseum to multiplatform-samples

- topics/compose/compose-compiler.md
Calling it "the Google" is funny, but that probably won't be standard until at least 2026
> Fix grammar referencing Google's announcement

- topics/compose/compose-compiler.md
Here we're trying to make sure that users don't take unnecessary steps during migration: referencing Compose compiler Maven artifacts directly is only necessary if there is no Gradle plugin to resolve them.
> fix: clarifying the migration steps

- topics/multiplatfrom-onboard/multiplatform-upgrade-app.md
I updated sample code in `topics/multiplatfrom-onboard/multiplatform-upgrade-app.md`.
In line 534, `await` is used in func `startObserving` but its function is not defined as async function. 
This misnotation caused build error in my environment, detailed environment is below.
Here are the document of lines 526 through 540 in `topics/multiplatfrom-onboard/multiplatform-upgrade-app.md`
```Swift
// ...
extension ContentView {
@MainActor
class ViewModel: ObservableObject {
@Published var greetings: [String] = []
-         func startObserving() {
+         func startObserving() async {
for await phrase in Greeting().greet() {
self.greetings.append(phrase)
}
}
}
}
```
- macOS Sonoma 14.5 (M1)
- Android Studio Koala 2024.1.1
- Xcode 15.4
- ['async' call in a function that does not support …
> Fix Sample Code: Add async notation at func startObserving in ContentView

- topics/compose/compose-compatibility-and-versioning.md
- topics/compose/compose-compiler.md
I got a little ahead of myself, isn't supposed to be merged before 2.0.10
> Revert "update: warning about instability of older dependencies"

- topics/compose/compose-navigation-routing.md
[KT-70402](https://youtrack.jetbrains.com/issue/KT-70402). This PR adds the Circuit framework to the list of third-party navigation libraries
> update: circuit framework added

- topics/compose-onboard/compose-multiplatform-create-first-app.md
There is no class now, but we could also make the run configuration class agnostic.
> fix: instruction broken with the latest wizard

- topics/compose/compose-compatibility-and-versioning.md
- topics/compose/compose-compiler.md
As a result of https://github.com/JetBrains/kotlin-web-site/pull/4349 we should align the warning text for the Compose compiler 2.0.0 version.
> Update 2.0.0 Compose compiler warning

- topics/compose/compose-compiler.md
Some options were move to the `featureFlags` set.
> update: 2.0.20 update to the composeCompiler {} block

- topics/compose/compose-compatibility-and-versioning.md
We removed the table and other content related to compatibility between Kotlin and Compose compiler, but there are enough users with older Kotlin versions who are left in the dark about this.
> fix: compatibility for older versions of Kotlin

- v.list
Not used in master, so updating it ahead of time.
> chore: new EAP version variable

- labels.list
The short names are not only identifiers, they are also visible in ToC.
> fix: visible label names

- topics/multiplatform-setup.md
In the latest Android Studio version, "Configure Kotlin Plugin Updates" doesn't exist anymore
> upd: remove mentions of "Configure Kotlin Plugin Updates"

- topics/multiplatform-integrate-in-existing-app.md
Changes are better visible in the rich diff: the step with adding the KMP plugin and AGP to the root build.gradle.kts is move to the beginning so that the user didn't get a scary Gradle error.
> fix: move a step earlier in the sequence to avoid Gradle sync error

- topics/whats-new/whats-new-compose-170.md
1. LazyGrid is now only 9% faster
2. Added a little promo of concurrent marking in the garbage collector
> updated performance numbers

- topics/compose/compose-viewmodel.md
- v.list
- [KWHF-1764](https://youtrack.jetbrains.com/issue/KWHF-1764/Web-feedback-from-Common-ViewModel-https-www.jetbrains.com-help-kotlin-multiplatform-dev-compose-viewmodel.html) Someone couldn't find the required imports, and there are more affected users on stackoverflow. I think it won't hurt to show key imports.
- [KWHF-1774](https://youtrack.jetbrains.com/issue/KWHF-1774/Web-feedback-from-Navigation-and-routing-https-www.jetbrains.com-help-kotlin-multiplatform-dev-compose-navigation-routing.html) Updated libs versions.
> web feedback: bumped versions, added imports

- topics/compose-onboard/compose-multiplatform-explore-composables.md
The `onClick` event handler does not invoke the greeting property  with the platform name.
> Update onClick description to reflect the code

- mpd.tree
- topics/kotlin-multiplatform-roadmap.md
Boiled down [original blogpost](https://blog.jetbrains.com/kotlin/2024/10/kotlin-multiplatform-development-roadmap-for-2025/), plus FAQ that the blogpost resulted in.
> updated: add the KMP roadmap page

- topics/compose/compose-multiplatform-resources-setup.md
- topics/compose/compose-multiplatform-resources-usage.md
In the course of expanding the resources documentation we lost the explicit mention of the way users need to import the generated class when they add Compose Multiplatform to an existing project.
> fix: mention Res import explicitly

- topics/compose/compose-multiplatform-resources-usage.md
For [CMP-7097](https://youtrack.jetbrains.com/issue/CMP-7097/Compose-multiplatform-resources-documentation-doesnt-explain-differences-with-Android). It should be clearer how multiplatform resources are different from [Android string formatting](https://developer.android.com/guide/topics/resources/string-resource#escaping_quotes).
> fix: clearer explanation of string templates

- topics/journal/cross-platform-mobile-development.md
Update a link and remove a piece of text.
> update: update cross-platform-mobile-development

- topics/journal/cross-platform-frameworks.md
- topics/journal/cross-platform-mobile-development.md
- topics/journal/kotlin-multiplatform-flutter.md
Update links and add internal links from other docs.
> update: update kotlin-multiplatform-flutter.md

- topics/whats-new/whats-new-compose-180.md
From this PR: https://github.com/JetBrains/compose-multiplatform-core/pull/1550
> update: additional breaking change for delayed coroutines in tests

- topics/multiplatform-onboard/multiplatform-create-first-app.md
The two code samples about the same piece of code are misaligned. If a reader is not familiar with import directives in Kotlin, they may be confused as to where `import java.util.Random` is supposed to go.
> fix: more transparent code sample

- topics/compose-onboard/compose-multiplatform-create-first-app.md
- topics/multiplatform-onboard/multiplatform-create-first-app.md
Some users automatically upgrade AGP when Android Studio suggests it, and then the wizard-generated project may not work anymore. Since this will continue to happen until KMP supports the latest AGP, a warning about this doesn't seem out of place.
> update: note on older AGP version

- topics/multiplatform-samples.md
Switched to Compose Navigation, and Android app is now (?) using fully shared code (instead of Jetpack Compose as we wrote before).
> update: updating Focus Bloom details

- topics/overview/supported-platforms.md
- Updated the iOS stability level from Beta to Stable in the platform support table.
- Reflecting the latest stability status of iOS support in Compose Multiplatform.
> Update iOS stability level to Stable

- topics/multiplatform-samples.md
The PeopleInSpace sample no longer supports watchOS but now works with Wear OS
> Apple watchOS -> Jetpack Compose on Wear OS

- topics/compose/compose-lifecycle.md
- topics/compose/compose-navigation-routing.md
- topics/compose/compose-navigation.md
- topics/compose/compose-viewmodel.md
Moved "how to add the dependency to use the library" to the main page
> upd: move setup earlier

- topics/compose-onboard/compose-multiplatform-modify-project.md
This PR updates the CMP tutorial to clarify that all dependencies for the `todaysDate()` function need to be taken from the `kotlinx.datetime` package and not `kotlin.time`.
> CMP tutorial: Small update to time instructions

- topics/compose/ios/compose-ios-touch.md
This PR fixes the class name in the docs, because `UIViewController` doesn't seem to have a constructor that takes `UIKitInteropProperties`.
> Fix view controller class name

- topics/development/multiplatform-build-native-binaries.md
- topics/development/multiplatform-compatibility-guide.md
- topics/tools/multiplatform-dsl-reference.md
- v.list
* [KT-60623](https://youtrack.jetbrains.com/issue/KT-60623)
* [KT-71068](https://youtrack.jetbrains.com/issue/KT-71068)
* [KT-66262](https://youtrack.jetbrains.com/issue/KT-66262)
> update: 2.2.0 changes

- topics/overview/faq.md
Was just reading through the docs and noticed that it currently mentions that `Compose Multiplatform is only Stable for Android and desktop at the moment`. iOS was recently made stable, hence, I'm updating this line.
https://www.jetbrains.com/help/kotlin-multiplatform-dev/faq.html#between-which-platforms-can-i-share-my-ui
> update iOS compose stability in FAQ

- mpd.tree
- topics/overview/use-cases-examples.md
The new documentation article about Kotlin Multiplatform and Compose Multiplatform use cases by teams and industries.
> feat: new documentation about KMP use cases

- topics/multiplatform-publish-apps.md
This PR updates the crash reports section following the removal of the bitcode part in [#4962](https://github.com/JetBrains/kotlin-web-site/pull/4962)
> update: native crash reports

- topics/development/multiplatform-publish-lib-setup.md
This PR updates the documentation section on klib cross compilation following stabilization in Kotlin 2.2.20.
> feat: stable klib cross-compilation
