README.md
Now includes "Docs & Examples" subsystem
=> Update YT link

topics/compose/compose-images-resources.md, topics/multiplatfrom-onboard/multiplatform-upgrade-app.md
* Removed unsupported AndroidManifest syntax
* New material3 imports and corresponding color→colorScheme change
* Corrected one of the emit() calls.
=> Example code fixes

topics/multiplatfrom-onboard/multiplatform-upgrade-app.md
As advised in https://youtrack.jetbrains.com/issue/KT-60734
=> New and improved sourceSets declaration

topics/multiplatform-run-tests.md
A code update and a couple of nitpicky corrections.
=> chore: several tiny updates and corrections

topics/overview/case-studies.md
Makes description more consistent with other company descriptions and clarifies why organizations work with us
=> Update Touchlab description in case-studies.md

topics/compose-onboard/compose-multiplatform-new-project.md
The padding for Column is missing.
=> Update the style sample code

topics/multiplatfrom-onboard/multiplatform-upgrade-app.md
The web wizard generation is fixed.
=> update: remove the SPM workaround

topics/multiplatform-publish-apps.md
To be merged after https://github.com/JetBrains/kotlin-web-site/pull/4143/commits
=> update: link to the privacy manifest article

topics/compose/compose-swiftui-integration.md, topics/compose/compose-test.md, topics/compose/compose-uikit-integration.md, topics/multiplatform-run-tests.md, topics/multiplatfrom-onboard/multiplatform-upgrade-app.md
Clarified a couple of paragraphs in the onboarding tutorial, and fixed a mistake in the testing tutorial.
=> fix: dealing with reported confusion

topics/compose/compose-lifecycle.md
See https://github.com/JetBrains/compose-multiplatform-core/pull/1319
=> update Lifecycle events mapping on iOS after changes in 1.6.0-beta3

topics/multiplatfrom-onboard/multiplatform-create-first-app.md
Add a period at the end of the sentence.
(cherry picked from commit fbd446162da1fc9371f4f8f3fd5938507a69b912)
=> fix: period at the end of a sentence

topics/compose/compose-compiler.md
https://youtrack.jetbrains.com/issue/KT-67387
=> update: new default value

project.ihp
Reverts JetBrains/kotlin-multiplatform-dev-docs#140
=> Revert "fix: correct version"

topics/development/multiplatform-spm-local-integration.md
Also rebuild special 1.9 version to support Compose
=> Describe migration from remote SPM integration in local SPM doc

topics/multiplatform-samples.md
This PR contains updates to the Compose Multiplatform samples page to clarify those samples that support web.
=> Update Multiplatform samples page

topics/overview/faq.md
updated according to [SEO recommendations](https://youtrack.jetbrains.com/issue/DM-4578/SEO-recommendations-for-KMP-pages-on-kotlinlang.org-and-jetbrains.com#focus=Comments-27-9900351.0-0)
=> minor SEO update: link to the main get started

topics/development/multiplatform-ktor-sqldelight.md
Born from this suggestion: https://github.com/JetBrains/kotlin-multiplatform-dev-docs/pull/250
=> update: add the -lsqlite3 linking flag for a static project

topics/compose/compose-compiler.md
Related pull request: https://github.com/JetBrains/kotlin-web-site/pull/4517
=> moved Compose compiler to kotlinlang

topics/compose/compose-multiplatform-resources-usage.md, topics/whats-new/whats-new-compose-170.md, v.list
This PR is tied to the changelog PR: https://github.com/JetBrains/compose-multiplatform/pull/5163
=> update: 1.7.1 version updates

mpd.tree, topics/compose-onboard/compose-multiplatform-create-first-app.md, topics/compose-onboard/compose-multiplatform-explore-composables.md, topics/compose-onboard/compose-multiplatform-modify-project.md, topics/compose-onboard/compose-multiplatform-new-project.md, topics/multiplatform-onboard/multiplatform-create-first-app.md, topics/multiplatform-onboard/multiplatform-dependencies.md, topics/multiplatform-onboard/multiplatform-update-ui.md, topics/multiplatform-onboard/multiplatform-upgrade-app.md, topics/multiplatform-onboard/multiplatform-wrap-up.md, topics/overview/get-started.topic
This PR aligns some of the structure between the two shared logic tutorials. It focuses on "multiplatform projects" and "Kotlin Multiplatform" or "Compose Multiplatform" apps.
=> Align wording of shared logic tutorials

topics/compose/compose-multiplatform-and-jetpack-compose.md
This PR adds a minor fix to the new Compose overview.
=> Minor fix in Compose overview

topics/overview/case-studies.topic
A slight touch-up for the new case studies layout.
=> fix: even height for icons

topics/kotlin-multiplatform-roadmap.md
To reflect the changes described here: https://blog.jetbrains.com/kotlin/2025/02/kotlin-multiplatform-tooling-shifting-gears/
=> update: update to the roadmap following the KMP Tooling shift

topics/compose/compose-compatibility-and-versioning.md, topics/whats-new/whats-new-compose-180.md
The support was added in https://youtrack.jetbrains.com/issue/CMP-223/Finish-Windows-ARM-64-support
=> Compose. Support Windows ARM

mpd.tree
=> update: update cross-platform-frameworks.md

topics/compose/ios/compose-ios-accessibility.md, topics/whats-new/whats-new-compose-180.md
From this PR: https://github.com/JetBrains/compose-multiplatform-core/pull/1780
=> update: iOS accessibility tree sync improvement

topics/multiplatform-samples.md
In last update, web platform added to shopping by kmp, also I've added deploy configuration on github to have check it live:
https://razaghimahdi.github.io/Shopping-By-KMP/
=> Update multiplatform-samples.md: shopping by kmp

topics/compose/compose-navigation-routing.md
Make sure that people who are trying out 1.8.0 remember to update Navigation as well.
=> update: a note about EAP compatibility

topics/whats-new/whats-new-compose-170.md, topics/whats-new/whats-new-compose-180.md
Mentioning the improvements measured in [CMP-7591](https://youtrack.jetbrains.com/issue/CMP-7591/) in the What's new.
=> update: switching to clang for Skia

topics/whats-new/whats-new-compose-180.md
https://youtrack.jetbrains.com/issue/CMP-8062
=> fix: more recent version of material-icons-core

topics/compose/compose-desktop-scrollbars.md, topics/multiplatform-run-tests.md
- "Desktop-specific components | Scrollbars": added info about scrolling using touchscreens, touchpads, and trackpads treated as mouse events.
- "Test your multiplatform app | Rules/tips for using tests in multiplatform projects": added info about the physics difference.
=> CMP-7446 scrolling differences

topics/compose-onboard/compose-multiplatform-create-first-app.md
This PR updates a gradle task following [this commit](https://github.com/JetBrains/kotlin-web-site/commit/515879bfcd205e385048874a626c20a96ec757c6#diff-acd079b03fa8a86fb7b262dd0675910e4bc10cdbb43ed4362550fcaef1ad1a11).
=> Update wasm gradle task.

topics/compose/compose-android-only-components.md
- Fixed broken links
- Replaced some GitHub links with API references
- The YouTrack link contained a private tag that could become public someday; removed the tag from the link for now
=> updated links

topics/multiplatform-onboard/multiplatform-create-first-app.md
Modifying a sentence to remove mentioning KMP wizard
=> chore: removing mention of the wizard in the project structure part

topics/multiplatform-samples.md
Added AutomotiveApp to shopping-by-kmp — the application is now compatible with Android Automotive OS, making it available for in-car systems.
=> Update multiplatform-samples.md: shopping-by-kmp

topics/journal/kotlin-multiplatform-flutter.md
upd: updated info about UI iteration for KMP and added a link to the blog post to the Kotlin Multiplatform and Flutter article
=> upd: kmp and flutter

topics/tools/compose-hot-reload.md
This PR updates the Compose Hot Reload documentation to save all files.
Approved by Maciej Procyk.
=> Add a save all instruction to Compose Hot Reload documentation

topics/multiplatform-publish-libraries.md, v.list
Along with this PR: https://github.com/Kotlin/multiplatform-library-template/pull/53/files
=> chore: update the multiplatform library template code
